#include <iostream.h>
#include<stdio.h>
#include<conio.h>
int main ()
{long double i,s,n;
clrscr();


for(i=3;i>=1;i--)
{
for(s=1;s<76;s++)
cout<<"þ";
cout<<"\n";
}

textcolor(RED);
{
for(i=7;i>=1;i--)
{
for(s=1;s<=1;s++)
cout<<"þ";
for(s=1;s<4;s++)
cout<<" ";
for(s=1;s<5;s++)
cout<<"!";
for(s=1;s<4;s++){
if(i>2){cout<<"*";}
else{cout<<" ";} }
for(s=1;s<5;s++)
cout<<"!";
for(s=1;s<4;s++){
if(i>2){cout<<"*";}
else{cout<<" ";} }
for(s=1;s<5;s++)
cout<<"!";
for(s=1;s<4;s++){
if(i>2){cout<<"*";}
else{cout<<" ";} }
for(s=1;s<5;s++)
cout<<"!";
for(s=1;s<4;s++){
if(i>2){cout<<"*";}
else{cout<<" ";} }
for(s=1;s<5;s++)
cout<<"!";
for(s=1;s<4;s++){
if(i>2){cout<<"*";}
else{cout<<" ";} }
for(s=1;s<5;s++)
cout<<"!";
for(s=1;s<4;s++){
if(i>2){cout<<"*";}
else{cout<<" ";} }
for(s=1;s<5;s++)
cout<<"!";
for(s=1;s<4;s++){
if(i>2){cout<<"*";}
else{cout<<" ";} }
for(s=1;s<5;s++)
cout<<"!";
for(s=1;s<4;s++){
if(i>2){cout<<"*";}
else{cout<<" ";} }
for(s=1;s<5;s++)
cout<<"!";
for(s=1;s<4;s++){
if(i>2){cout<<"*";}
else{cout<<" ";} }
for(s=1;s<5;s++)
cout<<"!";
for(s=1;s<4;s++)
cout<<" ";

for(s=1;s<=1;s++)
cout<<"þ";
cout<<"\n";
}
}



for(i=5;i>=1;i--)
{
for(s=1;s<76;s++)
cout<<"þ";
cout<<"\n";


}
     textcolor(YELLOW);
gotoxy(24,13);cout<<"ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿";
gotoxy(24,14);cout<<"³ þþþþþþ CASIO þþþþþþ ³";
gotoxy(24,15);cout<<"ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ";
getchar ();
return 0;
}








